clean:
	rm -f *.o *.elf *.map ../ps3manager_api_core/*.o stage2/*.o lv2/src/*.o lv1/src/*.o debug/src/*.o 
all:
	make -f Makefile_4.46 clean --no-print-directory
	make -f Makefile_4.46 --no-print-directory
	make -f Makefile_4.50 clean --no-print-directory
	make -f Makefile_4.50 --no-print-directory
	make -f Makefile_4.50D clean --no-print-directory
	make -f Makefile_4.50D --no-print-directory
	make -f Makefile_4.53 clean --no-print-directory
	make -f Makefile_4.53 --no-print-directory
	make -f Makefile_4.55 clean --no-print-directory
	make -f Makefile_4.55 --no-print-directory
	make -f Makefile_4.60 clean --no-print-directory
	make -f Makefile_4.60 --no-print-directory
	make -f Makefile_4.65 clean --no-print-directory
	make -f Makefile_4.65 --no-print-directory
	make -f Makefile_4.66 clean --no-print-directory
	make -f Makefile_4.66 --no-print-directory
	rm -f *.o *.elf *.map ../ps3manager_api_core/*.o stage2/*.o lv2/src/*.o lv1/src/*.o debug/src/*.o
